[package]
name = "integrityCheck"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
relative-path = "1.9.2"

[[bin]]
name = "integrityCheck"
path = "src/main.rs"

[lib]
name = "integrityCheckLib"
path = "src/lib/lib.rs"